In [55]:
#- Exercici 1
#Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

import numpy as np


# x = np.array([[0, 1, 2], [3, 4, 5]]) 
x=np.random.randint(1,100,10)

def analisis_de_matriz_x_de1dimension(x):
    if x.ndim > 1:
        print("Error: la matriu té més d'una dimensió")
    else:
        print ("mean:", np.mean (x))
        print ("mediana:", np.median (x))
        print ("percentil 50 (mediana):", np.percentile (x, 50))
        print ("percentil 25:", np.percentile (x, 25))
        print ("percentil 75:", np.percentile (x, 75))
        print ("desviación estándar:", np.std (x))
        print ("varianza:", np.var (x))
    
analisis_de_matriz_x_de1dimension(x)

mean: 53.9
mediana: 52.5
percentil 50 (mediana): 52.5
percentil 25: 42.5
percentil 75: 58.0
desviación estándar: 21.116107595861507
varianza: 445.89


In [97]:
#- Exercici 2
#Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.
import numpy as np

def quadrat_NxN (y, x=100):
    NxN = np.random.randint(x,size=(y,y))
    print(NxN)
    
quadrat_NxN(6)


[[57 47 94 79  1 40]
 [35 83 87 23 12  9]
 [71 63 72 96 61  8]
 [33 97 31 79 78 87]
 [57 90 41 59  1 86]
 [23 21 53 37 20 20]]


In [104]:
#- Exercici 3
#Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

#def Totals_fila_x_Tot_col(y,x)

import pandas as pd
data = [1,2,3],[5,6,7]




df = pd.DataFrame(data)
sum_column = df.sum(axis=0)
sum_fila = df.sum(axis=1)

print (sum_column)
print(sum_fila)

print(data)


0     6
1     8
2    10
dtype: int64
0     6
1    18
dtype: int64
([1, 2, 3], [5, 6, 7])


In [115]:
#- Exercici 3
#Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.


import pandas as pd
matriu = [1,2,3],[5,6,7]

def Totals_fila_x_Tot_col(matriu):
    df = pd.DataFrame(matriu)
    sum_column = df.sum(axis=0)
    sum_fila = df.sum(axis=1)
    print (sum_column)
    print(sum_fila)

Totals_fila_x_Tot_col(matriu)


0     6
1     8
2    10
dtype: int64
0     6
1    18
dtype: int64
([1, 2, 3], [5, 6, 7])


In [116]:
#- Exercici 4
#Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.


import numpy as np

## Calcularé el coeficient de correlació entre les notes dels alumnes, de les matèries de física i de matemàtiques. 

# Notes de matemàtiques:
P = np.array([2,3,4,4,5,6,6,7,7,8,10,10])

# Notes de física:
A = np.array([1,3,2,4,4,4,6,4,6,7,9,10])

def Coef_correlació (P,A):
    PA = P*A
    P2 = np.square (P)
    A2 = np.square (A)

    # Mitjanes arimètiques: 
    Pm = np.average(P)
    Am = np.average(A)

    # Covariança:
    Rm = np.average (PA) - Pm*Am

    # Desviació típica: 
    Dp = np.sqrt(np.average(P2) - np.square(Pm))
    Da = np.sqrt(np.average(A2) - np.square(Am))

    # Coeficient de correlació:
    r = round((Rm/(Dp*Da)),2)
    print("r = ", r)

Coef_correlació (P,A)

r =  0.94
